---

on:
  pull_request:
    branches:
      - master

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build - Multi-Platform
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          # load: true  # Can't load multi-platform but want to ensure building each is successful
          tags: artis3n/docker-amazonlinux2-ansible:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      # Is cached so no extra work besides exporting to local docker daemon
      - name: Build and Export
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64  # no arm64 in order to load:true successfully
          push: false
          load: true
          tags: artis3n/docker-amazonlinux2-ansible:ci
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Start test container
        run: docker run --name test-container -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro artis3n/docker-amazonlinux2-ansible:ci
      
      - name: Verify Ansible is present
        run: docker exec --tty test-container env TERM=xterm ansible --version
